### ISSUE TITLE
Stuck Login - Shibboleth 4.1.4

### ISSUE THREAD

**Issue by gianluDar** [italia/design-shibboleth-idp-theme#1]
Salve, 
in un'installazione Shibboleth 4.1.4 provando ad importare il tema tutto sembra andare a buon fine ma, in fase di login la pagina rimane '_bloccata_' come nello screen allegato. 
I file di log idp-warn e idp-process non segnalano nulla di particolare, l'installazione è su ambiente Ubuntu 20.04 Apache2 + Jetty
<img width="1022" alt="Schermata 2021-10-11 alle 18 43 38" src="https://user-images.githubusercontent.com/28647051/136826666-8aa4730b-a6c5-44f2-b118-d12687e294a6.png">
G.

**Comment by peppelinux** [comment]
Ciao Gianluca,
Questo Tema è stato usato fino a shibboleth 3.x, in seguito Unical ha migrato shibboleth a uniauth (sviluppato al suo interno).

Anyway, puoi risolvere, basta fare un diff tra l'attuale default template di shibboleth e quello di questa App e se ti andasse potresti anche proporre la patch con una pull request, la unirei con immenso piacere

**Comment by peppelinux** [comment]
Closed by
https://github.com/italia/design-shibboleth-idp-theme/pull/2
